# Generated by Django 6.0.6 on 2026-06-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=255)),
                ('team_b', models.CharField(max_length=255)),
                ('prob_a', models.FloatField(help_text='Model probability that team A wins')),
                ('favored', models.CharField(max_length=8)),
                ('confidence', models.FloatField(help_text='Confidence in the favored team (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
